#:schema node_modules/wrangler/config-schema.json
name = "queues-concurrency"
main = "src/index.ts"
compatibility_date = "2024-05-12"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.producers]]
binding = "MY_QUEUE"
queue = "queue-concurrency-test"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.consumers]]
queue = "queue-concurrency-test"
# Optional: Configure batching and retries: https://developers.cloudflare.com/queues/learning/batching-retries/
max_batch_size = 6
max_batch_timeout = 30
max_retries = 1
max_concurrency = 1
